// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: internal/virtual/proto/runner.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RunnerPlugin_Name_FullMethodName                      = "/proto.RunnerPlugin/Name"
	RunnerPlugin_Exec_FullMethodName                      = "/proto.RunnerPlugin/Exec"
	RunnerPlugin_CreateSchemaDDL_FullMethodName           = "/proto.RunnerPlugin/CreateSchemaDDL"
	RunnerPlugin_CreateTableDDL_FullMethodName            = "/proto.RunnerPlugin/CreateTableDDL"
	RunnerPlugin_CreateViewDDL_FullMethodName             = "/proto.RunnerPlugin/CreateViewDDL"
	RunnerPlugin_CreateMaterializedViewDDL_FullMethodName = "/proto.RunnerPlugin/CreateMaterializedViewDDL"
	RunnerPlugin_CreateStreamingTableDDL_FullMethodName   = "/proto.RunnerPlugin/CreateStreamingTableDDL"
	RunnerPlugin_TableExists_FullMethodName               = "/proto.RunnerPlugin/TableExists"
	RunnerPlugin_CreateIncrementalMergeDDL_FullMethodName = "/proto.RunnerPlugin/CreateIncrementalMergeDDL"
	RunnerPlugin_QueryCount_FullMethodName                = "/proto.RunnerPlugin/QueryCount"
)

// RunnerPluginClient is the client API for RunnerPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RunnerPluginClient interface {
	Name(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NameResponse, error)
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*Empty, error)
	CreateSchemaDDL(ctx context.Context, in *CreateSchemaRequest, opts ...grpc.CallOption) (*DDLResponse, error)
	CreateTableDDL(ctx context.Context, in *CreateTableRequest, opts ...grpc.CallOption) (*DDLResponse, error)
	CreateViewDDL(ctx context.Context, in *CreateViewRequest, opts ...grpc.CallOption) (*DDLResponse, error)
	CreateMaterializedViewDDL(ctx context.Context, in *CreateMaterializedViewRequest, opts ...grpc.CallOption) (*DDLResponse, error)
	CreateStreamingTableDDL(ctx context.Context, in *CreateStreamingTableRequest, opts ...grpc.CallOption) (*DDLResponse, error)
	TableExists(ctx context.Context, in *TableExistsRequest, opts ...grpc.CallOption) (*TableExistsResponse, error)
	CreateIncrementalMergeDDL(ctx context.Context, in *CreateIncrementalMergeRequest, opts ...grpc.CallOption) (*DDLResponse, error)
	QueryCount(ctx context.Context, in *QueryCountRequest, opts ...grpc.CallOption) (*QueryCountResponse, error)
}

type runnerPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewRunnerPluginClient(cc grpc.ClientConnInterface) RunnerPluginClient {
	return &runnerPluginClient{cc}
}

func (c *runnerPluginClient) Name(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NameResponse)
	err := c.cc.Invoke(ctx, RunnerPlugin_Name_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerPluginClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RunnerPlugin_Exec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerPluginClient) CreateSchemaDDL(ctx context.Context, in *CreateSchemaRequest, opts ...grpc.CallOption) (*DDLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DDLResponse)
	err := c.cc.Invoke(ctx, RunnerPlugin_CreateSchemaDDL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerPluginClient) CreateTableDDL(ctx context.Context, in *CreateTableRequest, opts ...grpc.CallOption) (*DDLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DDLResponse)
	err := c.cc.Invoke(ctx, RunnerPlugin_CreateTableDDL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerPluginClient) CreateViewDDL(ctx context.Context, in *CreateViewRequest, opts ...grpc.CallOption) (*DDLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DDLResponse)
	err := c.cc.Invoke(ctx, RunnerPlugin_CreateViewDDL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerPluginClient) CreateMaterializedViewDDL(ctx context.Context, in *CreateMaterializedViewRequest, opts ...grpc.CallOption) (*DDLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DDLResponse)
	err := c.cc.Invoke(ctx, RunnerPlugin_CreateMaterializedViewDDL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerPluginClient) CreateStreamingTableDDL(ctx context.Context, in *CreateStreamingTableRequest, opts ...grpc.CallOption) (*DDLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DDLResponse)
	err := c.cc.Invoke(ctx, RunnerPlugin_CreateStreamingTableDDL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerPluginClient) TableExists(ctx context.Context, in *TableExistsRequest, opts ...grpc.CallOption) (*TableExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TableExistsResponse)
	err := c.cc.Invoke(ctx, RunnerPlugin_TableExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerPluginClient) CreateIncrementalMergeDDL(ctx context.Context, in *CreateIncrementalMergeRequest, opts ...grpc.CallOption) (*DDLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DDLResponse)
	err := c.cc.Invoke(ctx, RunnerPlugin_CreateIncrementalMergeDDL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerPluginClient) QueryCount(ctx context.Context, in *QueryCountRequest, opts ...grpc.CallOption) (*QueryCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryCountResponse)
	err := c.cc.Invoke(ctx, RunnerPlugin_QueryCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunnerPluginServer is the server API for RunnerPlugin service.
// All implementations must embed UnimplementedRunnerPluginServer
// for forward compatibility.
type RunnerPluginServer interface {
	Name(context.Context, *Empty) (*NameResponse, error)
	Exec(context.Context, *ExecRequest) (*Empty, error)
	CreateSchemaDDL(context.Context, *CreateSchemaRequest) (*DDLResponse, error)
	CreateTableDDL(context.Context, *CreateTableRequest) (*DDLResponse, error)
	CreateViewDDL(context.Context, *CreateViewRequest) (*DDLResponse, error)
	CreateMaterializedViewDDL(context.Context, *CreateMaterializedViewRequest) (*DDLResponse, error)
	CreateStreamingTableDDL(context.Context, *CreateStreamingTableRequest) (*DDLResponse, error)
	TableExists(context.Context, *TableExistsRequest) (*TableExistsResponse, error)
	CreateIncrementalMergeDDL(context.Context, *CreateIncrementalMergeRequest) (*DDLResponse, error)
	QueryCount(context.Context, *QueryCountRequest) (*QueryCountResponse, error)
	mustEmbedUnimplementedRunnerPluginServer()
}

// UnimplementedRunnerPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRunnerPluginServer struct{}

func (UnimplementedRunnerPluginServer) Name(context.Context, *Empty) (*NameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Name not implemented")
}
func (UnimplementedRunnerPluginServer) Exec(context.Context, *ExecRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedRunnerPluginServer) CreateSchemaDDL(context.Context, *CreateSchemaRequest) (*DDLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSchemaDDL not implemented")
}
func (UnimplementedRunnerPluginServer) CreateTableDDL(context.Context, *CreateTableRequest) (*DDLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTableDDL not implemented")
}
func (UnimplementedRunnerPluginServer) CreateViewDDL(context.Context, *CreateViewRequest) (*DDLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateViewDDL not implemented")
}
func (UnimplementedRunnerPluginServer) CreateMaterializedViewDDL(context.Context, *CreateMaterializedViewRequest) (*DDLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMaterializedViewDDL not implemented")
}
func (UnimplementedRunnerPluginServer) CreateStreamingTableDDL(context.Context, *CreateStreamingTableRequest) (*DDLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateStreamingTableDDL not implemented")
}
func (UnimplementedRunnerPluginServer) TableExists(context.Context, *TableExistsRequest) (*TableExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TableExists not implemented")
}
func (UnimplementedRunnerPluginServer) CreateIncrementalMergeDDL(context.Context, *CreateIncrementalMergeRequest) (*DDLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateIncrementalMergeDDL not implemented")
}
func (UnimplementedRunnerPluginServer) QueryCount(context.Context, *QueryCountRequest) (*QueryCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryCount not implemented")
}
func (UnimplementedRunnerPluginServer) mustEmbedUnimplementedRunnerPluginServer() {}
func (UnimplementedRunnerPluginServer) testEmbeddedByValue()                      {}

// UnsafeRunnerPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunnerPluginServer will
// result in compilation errors.
type UnsafeRunnerPluginServer interface {
	mustEmbedUnimplementedRunnerPluginServer()
}

func RegisterRunnerPluginServer(s grpc.ServiceRegistrar, srv RunnerPluginServer) {
	// If the following call panics, it indicates UnimplementedRunnerPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RunnerPlugin_ServiceDesc, srv)
}

func _RunnerPlugin_Name_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerPluginServer).Name(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerPlugin_Name_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerPluginServer).Name(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerPlugin_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerPluginServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerPlugin_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerPluginServer).Exec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerPlugin_CreateSchemaDDL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerPluginServer).CreateSchemaDDL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerPlugin_CreateSchemaDDL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerPluginServer).CreateSchemaDDL(ctx, req.(*CreateSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerPlugin_CreateTableDDL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerPluginServer).CreateTableDDL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerPlugin_CreateTableDDL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerPluginServer).CreateTableDDL(ctx, req.(*CreateTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerPlugin_CreateViewDDL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerPluginServer).CreateViewDDL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerPlugin_CreateViewDDL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerPluginServer).CreateViewDDL(ctx, req.(*CreateViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerPlugin_CreateMaterializedViewDDL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMaterializedViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerPluginServer).CreateMaterializedViewDDL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerPlugin_CreateMaterializedViewDDL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerPluginServer).CreateMaterializedViewDDL(ctx, req.(*CreateMaterializedViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerPlugin_CreateStreamingTableDDL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStreamingTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerPluginServer).CreateStreamingTableDDL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerPlugin_CreateStreamingTableDDL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerPluginServer).CreateStreamingTableDDL(ctx, req.(*CreateStreamingTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerPlugin_TableExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TableExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerPluginServer).TableExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerPlugin_TableExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerPluginServer).TableExists(ctx, req.(*TableExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerPlugin_CreateIncrementalMergeDDL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIncrementalMergeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerPluginServer).CreateIncrementalMergeDDL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerPlugin_CreateIncrementalMergeDDL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerPluginServer).CreateIncrementalMergeDDL(ctx, req.(*CreateIncrementalMergeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerPlugin_QueryCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerPluginServer).QueryCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerPlugin_QueryCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerPluginServer).QueryCount(ctx, req.(*QueryCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RunnerPlugin_ServiceDesc is the grpc.ServiceDesc for RunnerPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunnerPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RunnerPlugin",
	HandlerType: (*RunnerPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Name",
			Handler:    _RunnerPlugin_Name_Handler,
		},
		{
			MethodName: "Exec",
			Handler:    _RunnerPlugin_Exec_Handler,
		},
		{
			MethodName: "CreateSchemaDDL",
			Handler:    _RunnerPlugin_CreateSchemaDDL_Handler,
		},
		{
			MethodName: "CreateTableDDL",
			Handler:    _RunnerPlugin_CreateTableDDL_Handler,
		},
		{
			MethodName: "CreateViewDDL",
			Handler:    _RunnerPlugin_CreateViewDDL_Handler,
		},
		{
			MethodName: "CreateMaterializedViewDDL",
			Handler:    _RunnerPlugin_CreateMaterializedViewDDL_Handler,
		},
		{
			MethodName: "CreateStreamingTableDDL",
			Handler:    _RunnerPlugin_CreateStreamingTableDDL_Handler,
		},
		{
			MethodName: "TableExists",
			Handler:    _RunnerPlugin_TableExists_Handler,
		},
		{
			MethodName: "CreateIncrementalMergeDDL",
			Handler:    _RunnerPlugin_CreateIncrementalMergeDDL_Handler,
		},
		{
			MethodName: "QueryCount",
			Handler:    _RunnerPlugin_QueryCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/virtual/proto/runner.proto",
}
