// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/virtual/proto/runner.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_virtual_proto_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_virtual_proto_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_virtual_proto_runner_proto_rawDescGZIP(), []int{0}
}

type NameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameResponse) Reset() {
	*x = NameResponse{}
	mi := &file_internal_virtual_proto_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameResponse) ProtoMessage() {}

func (x *NameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_virtual_proto_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameResponse.ProtoReflect.Descriptor instead.
func (*NameResponse) Descriptor() ([]byte, []int) {
	return file_internal_virtual_proto_runner_proto_rawDescGZIP(), []int{1}
}

func (x *NameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_internal_virtual_proto_runner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_virtual_proto_runner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_internal_virtual_proto_runner_proto_rawDescGZIP(), []int{2}
}

func (x *ExecRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

type CreateSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        string                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSchemaRequest) Reset() {
	*x = CreateSchemaRequest{}
	mi := &file_internal_virtual_proto_runner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSchemaRequest) ProtoMessage() {}

func (x *CreateSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_virtual_proto_runner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSchemaRequest.ProtoReflect.Descriptor instead.
func (*CreateSchemaRequest) Descriptor() ([]byte, []int) {
	return file_internal_virtual_proto_runner_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSchemaRequest) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

type CreateTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        string                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Table         string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	SelectSql     string                 `protobuf:"bytes,3,opt,name=select_sql,json=selectSql,proto3" json:"select_sql,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTableRequest) Reset() {
	*x = CreateTableRequest{}
	mi := &file_internal_virtual_proto_runner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTableRequest) ProtoMessage() {}

func (x *CreateTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_virtual_proto_runner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTableRequest.ProtoReflect.Descriptor instead.
func (*CreateTableRequest) Descriptor() ([]byte, []int) {
	return file_internal_virtual_proto_runner_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTableRequest) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *CreateTableRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *CreateTableRequest) GetSelectSql() string {
	if x != nil {
		return x.SelectSql
	}
	return ""
}

type CreateViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        string                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Table         string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	SelectSql     string                 `protobuf:"bytes,3,opt,name=select_sql,json=selectSql,proto3" json:"select_sql,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateViewRequest) Reset() {
	*x = CreateViewRequest{}
	mi := &file_internal_virtual_proto_runner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateViewRequest) ProtoMessage() {}

func (x *CreateViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_virtual_proto_runner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateViewRequest.ProtoReflect.Descriptor instead.
func (*CreateViewRequest) Descriptor() ([]byte, []int) {
	return file_internal_virtual_proto_runner_proto_rawDescGZIP(), []int{5}
}

func (x *CreateViewRequest) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *CreateViewRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *CreateViewRequest) GetSelectSql() string {
	if x != nil {
		return x.SelectSql
	}
	return ""
}

type CreateMaterializedViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        string                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Table         string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	SelectSql     string                 `protobuf:"bytes,3,opt,name=select_sql,json=selectSql,proto3" json:"select_sql,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMaterializedViewRequest) Reset() {
	*x = CreateMaterializedViewRequest{}
	mi := &file_internal_virtual_proto_runner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMaterializedViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMaterializedViewRequest) ProtoMessage() {}

func (x *CreateMaterializedViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_virtual_proto_runner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMaterializedViewRequest.ProtoReflect.Descriptor instead.
func (*CreateMaterializedViewRequest) Descriptor() ([]byte, []int) {
	return file_internal_virtual_proto_runner_proto_rawDescGZIP(), []int{6}
}

func (x *CreateMaterializedViewRequest) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *CreateMaterializedViewRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *CreateMaterializedViewRequest) GetSelectSql() string {
	if x != nil {
		return x.SelectSql
	}
	return ""
}

type CreateStreamingTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        string                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Table         string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Config        map[string]string      `protobuf:"bytes,3,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStreamingTableRequest) Reset() {
	*x = CreateStreamingTableRequest{}
	mi := &file_internal_virtual_proto_runner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStreamingTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStreamingTableRequest) ProtoMessage() {}

func (x *CreateStreamingTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_virtual_proto_runner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStreamingTableRequest.ProtoReflect.Descriptor instead.
func (*CreateStreamingTableRequest) Descriptor() ([]byte, []int) {
	return file_internal_virtual_proto_runner_proto_rawDescGZIP(), []int{7}
}

func (x *CreateStreamingTableRequest) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *CreateStreamingTableRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *CreateStreamingTableRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type TableExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        string                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Table         string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableExistsRequest) Reset() {
	*x = TableExistsRequest{}
	mi := &file_internal_virtual_proto_runner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableExistsRequest) ProtoMessage() {}

func (x *TableExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_virtual_proto_runner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableExistsRequest.ProtoReflect.Descriptor instead.
func (*TableExistsRequest) Descriptor() ([]byte, []int) {
	return file_internal_virtual_proto_runner_proto_rawDescGZIP(), []int{8}
}

func (x *TableExistsRequest) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *TableExistsRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

type TableExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableExistsResponse) Reset() {
	*x = TableExistsResponse{}
	mi := &file_internal_virtual_proto_runner_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableExistsResponse) ProtoMessage() {}

func (x *TableExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_virtual_proto_runner_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableExistsResponse.ProtoReflect.Descriptor instead.
func (*TableExistsResponse) Descriptor() ([]byte, []int) {
	return file_internal_virtual_proto_runner_proto_rawDescGZIP(), []int{9}
}

func (x *TableExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type CreateIncrementalMergeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        string                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Table         string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	SelectSql     string                 `protobuf:"bytes,3,opt,name=select_sql,json=selectSql,proto3" json:"select_sql,omitempty"`
	Config        map[string]string      `protobuf:"bytes,4,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIncrementalMergeRequest) Reset() {
	*x = CreateIncrementalMergeRequest{}
	mi := &file_internal_virtual_proto_runner_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIncrementalMergeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIncrementalMergeRequest) ProtoMessage() {}

func (x *CreateIncrementalMergeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_virtual_proto_runner_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIncrementalMergeRequest.ProtoReflect.Descriptor instead.
func (*CreateIncrementalMergeRequest) Descriptor() ([]byte, []int) {
	return file_internal_virtual_proto_runner_proto_rawDescGZIP(), []int{10}
}

func (x *CreateIncrementalMergeRequest) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *CreateIncrementalMergeRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *CreateIncrementalMergeRequest) GetSelectSql() string {
	if x != nil {
		return x.SelectSql
	}
	return ""
}

func (x *CreateIncrementalMergeRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type QueryCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCountRequest) Reset() {
	*x = QueryCountRequest{}
	mi := &file_internal_virtual_proto_runner_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCountRequest) ProtoMessage() {}

func (x *QueryCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_virtual_proto_runner_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCountRequest.ProtoReflect.Descriptor instead.
func (*QueryCountRequest) Descriptor() ([]byte, []int) {
	return file_internal_virtual_proto_runner_proto_rawDescGZIP(), []int{11}
}

func (x *QueryCountRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

type QueryCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCountResponse) Reset() {
	*x = QueryCountResponse{}
	mi := &file_internal_virtual_proto_runner_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCountResponse) ProtoMessage() {}

func (x *QueryCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_virtual_proto_runner_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCountResponse.ProtoReflect.Descriptor instead.
func (*QueryCountResponse) Descriptor() ([]byte, []int) {
	return file_internal_virtual_proto_runner_proto_rawDescGZIP(), []int{12}
}

func (x *QueryCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DDLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ddl           string                 `protobuf:"bytes,1,opt,name=ddl,proto3" json:"ddl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DDLResponse) Reset() {
	*x = DDLResponse{}
	mi := &file_internal_virtual_proto_runner_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DDLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DDLResponse) ProtoMessage() {}

func (x *DDLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_virtual_proto_runner_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DDLResponse.ProtoReflect.Descriptor instead.
func (*DDLResponse) Descriptor() ([]byte, []int) {
	return file_internal_virtual_proto_runner_proto_rawDescGZIP(), []int{13}
}

func (x *DDLResponse) GetDdl() string {
	if x != nil {
		return x.Ddl
	}
	return ""
}

var File_internal_virtual_proto_runner_proto protoreflect.FileDescriptor

const file_internal_virtual_proto_runner_proto_rawDesc = "" +
	"\n" +
	"#internal/virtual/proto/runner.proto\x12\x05proto\"\a\n" +
	"\x05Empty\"\"\n" +
	"\fNameResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1f\n" +
	"\vExecRequest\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\"-\n" +
	"\x13CreateSchemaRequest\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\"a\n" +
	"\x12CreateTableRequest\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x12\x1d\n" +
	"\n" +
	"select_sql\x18\x03 \x01(\tR\tselectSql\"`\n" +
	"\x11CreateViewRequest\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x12\x1d\n" +
	"\n" +
	"select_sql\x18\x03 \x01(\tR\tselectSql\"l\n" +
	"\x1dCreateMaterializedViewRequest\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x12\x1d\n" +
	"\n" +
	"select_sql\x18\x03 \x01(\tR\tselectSql\"\xce\x01\n" +
	"\x1bCreateStreamingTableRequest\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x12F\n" +
	"\x06config\x18\x03 \x03(\v2..proto.CreateStreamingTableRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\x12TableExistsRequest\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\"-\n" +
	"\x13TableExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"\xf1\x01\n" +
	"\x1dCreateIncrementalMergeRequest\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x12\x1d\n" +
	"\n" +
	"select_sql\x18\x03 \x01(\tR\tselectSql\x12H\n" +
	"\x06config\x18\x04 \x03(\v20.proto.CreateIncrementalMergeRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"%\n" +
	"\x11QueryCountRequest\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\"*\n" +
	"\x12QueryCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"\x1f\n" +
	"\vDDLResponse\x12\x10\n" +
	"\x03ddl\x18\x01 \x01(\tR\x03ddl2\xb0\x05\n" +
	"\fRunnerPlugin\x12)\n" +
	"\x04Name\x12\f.proto.Empty\x1a\x13.proto.NameResponse\x12(\n" +
	"\x04Exec\x12\x12.proto.ExecRequest\x1a\f.proto.Empty\x12A\n" +
	"\x0fCreateSchemaDDL\x12\x1a.proto.CreateSchemaRequest\x1a\x12.proto.DDLResponse\x12?\n" +
	"\x0eCreateTableDDL\x12\x19.proto.CreateTableRequest\x1a\x12.proto.DDLResponse\x12=\n" +
	"\rCreateViewDDL\x12\x18.proto.CreateViewRequest\x1a\x12.proto.DDLResponse\x12U\n" +
	"\x19CreateMaterializedViewDDL\x12$.proto.CreateMaterializedViewRequest\x1a\x12.proto.DDLResponse\x12Q\n" +
	"\x17CreateStreamingTableDDL\x12\".proto.CreateStreamingTableRequest\x1a\x12.proto.DDLResponse\x12D\n" +
	"\vTableExists\x12\x19.proto.TableExistsRequest\x1a\x1a.proto.TableExistsResponse\x12U\n" +
	"\x19CreateIncrementalMergeDDL\x12$.proto.CreateIncrementalMergeRequest\x1a\x12.proto.DDLResponse\x12A\n" +
	"\n" +
	"QueryCount\x12\x18.proto.QueryCountRequest\x1a\x19.proto.QueryCountResponseB>Z<github.com/drover-org/drover-sqlforge/internal/virtual/protob\x06proto3"

var (
	file_internal_virtual_proto_runner_proto_rawDescOnce sync.Once
	file_internal_virtual_proto_runner_proto_rawDescData []byte
)

func file_internal_virtual_proto_runner_proto_rawDescGZIP() []byte {
	file_internal_virtual_proto_runner_proto_rawDescOnce.Do(func() {
		file_internal_virtual_proto_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_virtual_proto_runner_proto_rawDesc), len(file_internal_virtual_proto_runner_proto_rawDesc)))
	})
	return file_internal_virtual_proto_runner_proto_rawDescData
}

var file_internal_virtual_proto_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_internal_virtual_proto_runner_proto_goTypes = []any{
	(*Empty)(nil),                         // 0: proto.Empty
	(*NameResponse)(nil),                  // 1: proto.NameResponse
	(*ExecRequest)(nil),                   // 2: proto.ExecRequest
	(*CreateSchemaRequest)(nil),           // 3: proto.CreateSchemaRequest
	(*CreateTableRequest)(nil),            // 4: proto.CreateTableRequest
	(*CreateViewRequest)(nil),             // 5: proto.CreateViewRequest
	(*CreateMaterializedViewRequest)(nil), // 6: proto.CreateMaterializedViewRequest
	(*CreateStreamingTableRequest)(nil),   // 7: proto.CreateStreamingTableRequest
	(*TableExistsRequest)(nil),            // 8: proto.TableExistsRequest
	(*TableExistsResponse)(nil),           // 9: proto.TableExistsResponse
	(*CreateIncrementalMergeRequest)(nil), // 10: proto.CreateIncrementalMergeRequest
	(*QueryCountRequest)(nil),             // 11: proto.QueryCountRequest
	(*QueryCountResponse)(nil),            // 12: proto.QueryCountResponse
	(*DDLResponse)(nil),                   // 13: proto.DDLResponse
	nil,                                   // 14: proto.CreateStreamingTableRequest.ConfigEntry
	nil,                                   // 15: proto.CreateIncrementalMergeRequest.ConfigEntry
}
var file_internal_virtual_proto_runner_proto_depIdxs = []int32{
	14, // 0: proto.CreateStreamingTableRequest.config:type_name -> proto.CreateStreamingTableRequest.ConfigEntry
	15, // 1: proto.CreateIncrementalMergeRequest.config:type_name -> proto.CreateIncrementalMergeRequest.ConfigEntry
	0,  // 2: proto.RunnerPlugin.Name:input_type -> proto.Empty
	2,  // 3: proto.RunnerPlugin.Exec:input_type -> proto.ExecRequest
	3,  // 4: proto.RunnerPlugin.CreateSchemaDDL:input_type -> proto.CreateSchemaRequest
	4,  // 5: proto.RunnerPlugin.CreateTableDDL:input_type -> proto.CreateTableRequest
	5,  // 6: proto.RunnerPlugin.CreateViewDDL:input_type -> proto.CreateViewRequest
	6,  // 7: proto.RunnerPlugin.CreateMaterializedViewDDL:input_type -> proto.CreateMaterializedViewRequest
	7,  // 8: proto.RunnerPlugin.CreateStreamingTableDDL:input_type -> proto.CreateStreamingTableRequest
	8,  // 9: proto.RunnerPlugin.TableExists:input_type -> proto.TableExistsRequest
	10, // 10: proto.RunnerPlugin.CreateIncrementalMergeDDL:input_type -> proto.CreateIncrementalMergeRequest
	11, // 11: proto.RunnerPlugin.QueryCount:input_type -> proto.QueryCountRequest
	1,  // 12: proto.RunnerPlugin.Name:output_type -> proto.NameResponse
	0,  // 13: proto.RunnerPlugin.Exec:output_type -> proto.Empty
	13, // 14: proto.RunnerPlugin.CreateSchemaDDL:output_type -> proto.DDLResponse
	13, // 15: proto.RunnerPlugin.CreateTableDDL:output_type -> proto.DDLResponse
	13, // 16: proto.RunnerPlugin.CreateViewDDL:output_type -> proto.DDLResponse
	13, // 17: proto.RunnerPlugin.CreateMaterializedViewDDL:output_type -> proto.DDLResponse
	13, // 18: proto.RunnerPlugin.CreateStreamingTableDDL:output_type -> proto.DDLResponse
	9,  // 19: proto.RunnerPlugin.TableExists:output_type -> proto.TableExistsResponse
	13, // 20: proto.RunnerPlugin.CreateIncrementalMergeDDL:output_type -> proto.DDLResponse
	12, // 21: proto.RunnerPlugin.QueryCount:output_type -> proto.QueryCountResponse
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_internal_virtual_proto_runner_proto_init() }
func file_internal_virtual_proto_runner_proto_init() {
	if File_internal_virtual_proto_runner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_virtual_proto_runner_proto_rawDesc), len(file_internal_virtual_proto_runner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_virtual_proto_runner_proto_goTypes,
		DependencyIndexes: file_internal_virtual_proto_runner_proto_depIdxs,
		MessageInfos:      file_internal_virtual_proto_runner_proto_msgTypes,
	}.Build()
	File_internal_virtual_proto_runner_proto = out.File
	file_internal_virtual_proto_runner_proto_goTypes = nil
	file_internal_virtual_proto_runner_proto_depIdxs = nil
}
